var bankName;
bankName = "SBI";
console.log(bankName);
console.log(typeof bankName);
var marks = "90%";
console.log(marks);
console.log(typeof marks);
var isWorking;
console.log(isWorking);
console.log(typeof isWorking);
isWorking = true;
console.log(isWorking);
console.log(typeof isWorking);
var totalCount = "Hundred and Seven";
console.log(totalCount);
console.log(typeof totalCount);
totalCount = 107;
console.log(totalCount);
console.log(typeof totalCount);
console.log("=======================================");
var salary = null;
console.log(typeof salary);
salary = 40000.5; //
var typeOfSalary = typeof salary;
console.log("salary=>", salary, "typeof salary =>", typeOfSalary);
salary = "Forty Thousand";
var salaryTypeOf = typeof salary;
console.log("salary=>", salary, "typeof=>", salaryTypeOf);
